baseURL = "https://dimzakki.com/"
title = "Dim雑記"
DefaultContentLanguage = "ja"
languageCode = "ja-JP"
theme = "mainroad"
hasCJKLanguage = true
summarylength = 120
enableGitInfo = "true" # 最終更新日をgitから取得
timeout = "60s"

[services.googleAnalytics]
  ID = "G-YZ8ZTS9C8C" # アナリティクスのトラッキングID

[permalinks]
  post = "/:contentbasename/"

[Params]
  Subtitle = "ITエンジニアが運営する雑記ブログです"
  description = "ITエンジニアが運営する雑記ブログです"
  schema = true
  post_meta = ["date", "categories"]
  highlightColor = "#0095d9"
  dateformat = "2006-01-02"
  customCSS = ["/css/custom.css"]
  toc = true
  price1 = "税込37,730円（2024/08/23時点）"

[Params.sidebar]
  home = "right"
  list = "right"
  single = "right"
  widgets = ["adsense", "profile", "ranking", "categories", "taglist", "recent", "archives", "related", "adsense2"]

[Params.widgets]
  recent_num = 5
  categories_counter = true
  tags_counter = true
  
[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[related]
  includeNewer = true
[[related.indices]]
  name = "tags"
  weight = 80
[[related.indices]]
  name = "categories"
  weight = 60

[[Menus.main]]
  Name = "当サイトについて"
  URL = "/about"
  weight = 10
[[Menus.main]]
  Name = "プロフィール"
  URL = "/profile"
  weight = 20
[[Menus.main]]
  Name = "IT資格一覧"
  URL = "/it-qualification"
  weight = 30
[[Menus.main]]
  Name = "サイト内全文検索"
  URL = "/search"
  weight = 40
[[Menus.main]]
  Name = "お問い合わせ"
  URL = "/contact"
  weight = 50
[[Menus.footer]]
  Name = "プライバシーポリシー"
  URL = "/privacy-policy"

[markup.goldmark.renderer]
  unsafe = true